#ifndef _ZONES_H
#define _ZONES_H

#define UTZ_TIGHT

const urule_packed_t zone_rules[32];

#ifndef UTZ_TIGHT
const char zone_abrevs[294];

#define MAX_ABREV_FORMATTER_LEN 11

#endif

const uzone_packed_t zone_defns[61];
#define UTZ_ADELAIDE         &zone_defns[ 44]
#define UTZ_ALMATY           &zone_defns[ 20]
#define UTZ_AMMAN            &zone_defns[ 21]
#define UTZ_AMSTERDAM        &zone_defns[ 51]
#define UTZ_ANADYR           &zone_defns[ 22]
#define UTZ_AQTOBE           &zone_defns[ 23]
#define UTZ_ARUBA            &zone_defns[ 13]
#define UTZ_ASUNCION         &zone_defns[  8]
#define UTZ_AUCKLAND         &zone_defns[ 57]
#define UTZ_BAGHDAD          &zone_defns[ 24]
#define UTZ_BAHIA            &zone_defns[  7]
#define UTZ_BAHRAIN          &zone_defns[ 41]
#define UTZ_BAKU             &zone_defns[ 25]
#define UTZ_BANGKOK          &zone_defns[ 26]
#define UTZ_BARNAUL          &zone_defns[ 26]
#define UTZ_BELIZE           &zone_defns[  9]
#define UTZ_BERLIN           &zone_defns[ 51]
#define UTZ_BLANTYRE         &zone_defns[  2]
#define UTZ_BOGOTA           &zone_defns[ 10]
#define UTZ_BRISBANE         &zone_defns[ 45]
#define UTZ_BRUNEI           &zone_defns[ 27]
#define UTZ_BUENOS_AIRES     &zone_defns[  6]
#define UTZ_CAIRO            &zone_defns[  0]
#define UTZ_CANARY           &zone_defns[ 43]
#define UTZ_CHATHAM          &zone_defns[ 58]
#define UTZ_CHISINAU         &zone_defns[ 52]
#define UTZ_CHITA            &zone_defns[ 28]
#define UTZ_COLOMBO          &zone_defns[ 29]
#define UTZ_COSTA_RICA       &zone_defns[ 11]
#define UTZ_CUIABA           &zone_defns[ 12]
#define UTZ_CURACAO          &zone_defns[ 13]
#define UTZ_DAR_ES_SALAAM    &zone_defns[  3]
#define UTZ_DARWIN           &zone_defns[ 46]
#define UTZ_DHAKA            &zone_defns[ 30]
#define UTZ_DUBAI            &zone_defns[ 31]
#define UTZ_EASTER           &zone_defns[ 59]
#define UTZ_EUCLA            &zone_defns[ 47]
#define UTZ_GABORONE         &zone_defns[  2]
#define UTZ_GALAPAGOS        &zone_defns[ 60]
#define UTZ_GUATEMALA        &zone_defns[ 11]
#define UTZ_HARARE           &zone_defns[  2]
#define UTZ_HO_CHI_MINH      &zone_defns[ 26]
#define UTZ_HONG_KONG        &zone_defns[ 32]
#define UTZ_IRKUTSK          &zone_defns[ 27]
#define UTZ_JAKARTA          &zone_defns[ 33]
#define UTZ_JAYAPURA         &zone_defns[ 34]
#define UTZ_JERUSALEM        &zone_defns[ 35]
#define UTZ_JOHANNESBURG     &zone_defns[  1]
#define UTZ_KALININGRAD      &zone_defns[ 53]
#define UTZ_KAMCHATKA        &zone_defns[ 22]
#define UTZ_KARACHI          &zone_defns[ 36]
#define UTZ_KATHMANDU        &zone_defns[ 37]
#define UTZ_KIEV             &zone_defns[ 54]
#define UTZ_KIROV            &zone_defns[ 41]
#define UTZ_KRASNOYARSK      &zone_defns[ 26]
#define UTZ_KUALA_LUMPUR     &zone_defns[ 27]
#define UTZ_KUWAIT           &zone_defns[ 41]
#define UTZ_LA_PAZ           &zone_defns[ 14]
#define UTZ_LIMA             &zone_defns[ 10]
#define UTZ_LONDON           &zone_defns[ 55]
#define UTZ_LORD_HOWE        &zone_defns[ 48]
#define UTZ_LUSAKA           &zone_defns[  2]
#define UTZ_MACAU            &zone_defns[ 38]
#define UTZ_MACQUARIE        &zone_defns[ 19]
#define UTZ_MADRID           &zone_defns[ 51]
#define UTZ_MAGADAN          &zone_defns[ 19]
#define UTZ_MAKASSAR         &zone_defns[ 39]
#define UTZ_MANAGUA          &zone_defns[ 11]
#define UTZ_MANAUS           &zone_defns[ 14]
#define UTZ_MANILA           &zone_defns[ 40]
#define UTZ_MAPUTO           &zone_defns[  2]
#define UTZ_MASERU           &zone_defns[  1]
#define UTZ_MAURITIUS        &zone_defns[ 25]
#define UTZ_MBABANE          &zone_defns[  1]
#define UTZ_MINSK            &zone_defns[ 41]
#define UTZ_MONTEVIDEO       &zone_defns[  6]
#define UTZ_MOSCOW           &zone_defns[ 56]
#define UTZ_MUSCAT           &zone_defns[ 31]
#define UTZ_NAIROBI          &zone_defns[  3]
#define UTZ_NORONHA          &zone_defns[ 15]
#define UTZ_NOVOSIBIRSK      &zone_defns[ 26]
#define UTZ_OMSK             &zone_defns[ 20]
#define UTZ_ORAL             &zone_defns[ 23]
#define UTZ_OSLO             &zone_defns[ 51]
#define UTZ_PARIS            &zone_defns[ 51]
#define UTZ_PERTH            &zone_defns[ 49]
#define UTZ_QATAR            &zone_defns[ 41]
#define UTZ_RIO_BRANCO       &zone_defns[ 16]
#define UTZ_RIYADH           &zone_defns[ 41]
#define UTZ_ROME             &zone_defns[ 51]
#define UTZ_SAKHALIN         &zone_defns[ 19]
#define UTZ_SAMARA           &zone_defns[ 31]
#define UTZ_SAN_LUIS         &zone_defns[  7]
#define UTZ_SANTIAGO         &zone_defns[ 17]
#define UTZ_SAO_PAULO        &zone_defns[ 18]
#define UTZ_SARATOV          &zone_defns[ 31]
#define UTZ_SHANGHAI         &zone_defns[ 38]
#define UTZ_SINGAPORE        &zone_defns[ 27]
#define UTZ_SREDNEKOLYMSK    &zone_defns[ 19]
#define UTZ_SYDNEY           &zone_defns[ 50]
#define UTZ_TASHKENT         &zone_defns[ 23]
#define UTZ_TEGUCIGALPA      &zone_defns[ 11]
#define UTZ_TUNIS            &zone_defns[  4]
#define UTZ_URUMQI           &zone_defns[ 20]
#define UTZ_VLADIVOSTOK      &zone_defns[ 42]
#define UTZ_WINDHOEK         &zone_defns[  5]
#define UTZ_YEKATERINBURG    &zone_defns[ 23]

#ifndef UTZ_TIGHT
#define NUM_ZONE_NAMES 107
#define MAX_ZONE_NAME_LEN 14

const unsigned char zone_names[990];
#endif

#endif /* _ZONES_H */