#ifndef _ZONES_H
#define _ZONES_H

const urule_packed_t zone_rules[32];
const char zone_abrevs[204];

#define MAX_ABREV_FORMATTER_LEN 7

const uzone_packed_t zone_defns[43];
#define UTZ_ADELAIDE            &zone_defns[ 29]
#define UTZ_AHMEDABAD           &zone_defns[ 22]
#define UTZ_ANKARA              &zone_defns[ 37]
#define UTZ_ARUBA               &zone_defns[  6]
#define UTZ_ATLANTA             &zone_defns[ 10]
#define UTZ_AUCKLAND            &zone_defns[ 40]
#define UTZ_BAHRAIN             &zone_defns[ 25]
#define UTZ_BANGALORE           &zone_defns[ 22]
#define UTZ_BANGKOK             &zone_defns[ 15]
#define UTZ_BARCELONA           &zone_defns[ 35]
#define UTZ_BEIJING             &zone_defns[ 23]
#define UTZ_BELO_HORIZONTE      &zone_defns[ 14]
#define UTZ_BERLIN              &zone_defns[ 35]
#define UTZ_BLANTYRE            &zone_defns[  2]
#define UTZ_BOSTON              &zone_defns[ 10]
#define UTZ_BRISBANE            &zone_defns[ 30]
#define UTZ_BUENOS_AIRES        &zone_defns[  4]
#define UTZ_CAIRO               &zone_defns[  0]
#define UTZ_CHANGZHOU           &zone_defns[ 23]
#define UTZ_CHATHAM             &zone_defns[ 41]
#define UTZ_CHENGDU             &zone_defns[ 23]
#define UTZ_CHENNAI             &zone_defns[ 22]
#define UTZ_CHICAGO             &zone_defns[  5]
#define UTZ_CHISINAU            &zone_defns[ 36]
#define UTZ_CHONGQING           &zone_defns[ 23]
#define UTZ_CURACAO             &zone_defns[  6]
#define UTZ_DALLASFORT_WORTH    &zone_defns[  5]
#define UTZ_DAR_ES_SALAAM       &zone_defns[  3]
#define UTZ_DARWIN              &zone_defns[ 31]
#define UTZ_DELHI               &zone_defns[ 22]
#define UTZ_DHAKA               &zone_defns[ 16]
#define UTZ_DUBAI               &zone_defns[ 17]
#define UTZ_EASTER              &zone_defns[ 42]
#define UTZ_GABORONE            &zone_defns[  2]
#define UTZ_GUADALAJARA         &zone_defns[  9]
#define UTZ_GUANGZHOU           &zone_defns[ 23]
#define UTZ_HAMBURG             &zone_defns[ 35]
#define UTZ_HANGZHOU            &zone_defns[ 23]
#define UTZ_HARARE              &zone_defns[  2]
#define UTZ_HO_CHI_MINH         &zone_defns[ 15]
#define UTZ_HONG_KONG           &zone_defns[ 18]
#define UTZ_HOUSTON             &zone_defns[  5]
#define UTZ_HYDERABAD           &zone_defns[ 22]
#define UTZ_INLAND_EMPIRE       &zone_defns[  7]
#define UTZ_ISTANBUL            &zone_defns[ 37]
#define UTZ_JERUSALEM           &zone_defns[ 19]
#define UTZ_JINAN               &zone_defns[ 23]
#define UTZ_JOHANNESBURG        &zone_defns[  1]
#define UTZ_KARACHI             &zone_defns[ 20]
#define UTZ_KATHMANDU           &zone_defns[ 21]
#define UTZ_KOLKATA             &zone_defns[ 22]
#define UTZ_KUWAIT              &zone_defns[ 25]
#define UTZ_LAHORE              &zone_defns[ 20]
#define UTZ_LONDON              &zone_defns[ 38]
#define UTZ_LORD_HOWE           &zone_defns[ 32]
#define UTZ_LOS_ANGELES         &zone_defns[  7]
#define UTZ_LUSAKA              &zone_defns[  2]
#define UTZ_MACAU               &zone_defns[ 23]
#define UTZ_MADRID              &zone_defns[ 35]
#define UTZ_MAKASSAR            &zone_defns[ 24]
#define UTZ_MANAUS              &zone_defns[  8]
#define UTZ_MAPUTO              &zone_defns[  2]
#define UTZ_MASERU              &zone_defns[  1]
#define UTZ_MBABANE             &zone_defns[  1]
#define UTZ_MEXICO_CITY         &zone_defns[  9]
#define UTZ_MIAMI               &zone_defns[ 10]
#define UTZ_MILAN               &zone_defns[ 35]
#define UTZ_MOSCOW              &zone_defns[ 39]
#define UTZ_MUMBAI              &zone_defns[ 22]
#define UTZ_MUNICH              &zone_defns[ 35]
#define UTZ_MUSCAT              &zone_defns[ 17]
#define UTZ_NAGOYA              &zone_defns[ 27]
#define UTZ_NAIROBI             &zone_defns[  3]
#define UTZ_NANCHANG            &zone_defns[ 23]
#define UTZ_NANJING             &zone_defns[ 23]
#define UTZ_NEW_YORK            &zone_defns[ 10]
#define UTZ_NORONHA             &zone_defns[ 11]
#define UTZ_OSAKA               &zone_defns[ 27]
#define UTZ_OSLO                &zone_defns[ 35]
#define UTZ_PERTH               &zone_defns[ 33]
#define UTZ_PHILADELPHIA        &zone_defns[ 10]
#define UTZ_PUNE                &zone_defns[ 22]
#define UTZ_QATAR               &zone_defns[ 25]
#define UTZ_QINGDAO             &zone_defns[ 23]
#define UTZ_RHINERUHR           &zone_defns[ 35]
#define UTZ_RIO_BRANCO          &zone_defns[ 12]
#define UTZ_RIO_DE_JANEIRO      &zone_defns[ 14]
#define UTZ_RIYADH              &zone_defns[ 25]
#define UTZ_ROME                &zone_defns[ 35]
#define UTZ_SAN_FRANCISCO       &zone_defns[  7]
#define UTZ_SANTIAGO            &zone_defns[ 13]
#define UTZ_SAO_PAULO           &zone_defns[ 14]
#define UTZ_SHANGHAI            &zone_defns[ 23]
#define UTZ_SHENYANG            &zone_defns[ 23]
#define UTZ_SHENZHEN            &zone_defns[ 23]
#define UTZ_SINGAPORE           &zone_defns[ 26]
#define UTZ_ST_BARTHELEMY       &zone_defns[  6]
#define UTZ_STUTTGART           &zone_defns[ 35]
#define UTZ_SURAT               &zone_defns[ 22]
#define UTZ_SYDNEY              &zone_defns[ 34]
#define UTZ_TIANJIN             &zone_defns[ 23]
#define UTZ_TOKYO               &zone_defns[ 27]
#define UTZ_TORTOLA             &zone_defns[  6]
#define UTZ_URUMQI              &zone_defns[ 28]
#define UTZ_WASHINGTON_DC       &zone_defns[ 10]
#define UTZ_WENZHOU             &zone_defns[ 23]
#define UTZ_WUHAN               &zone_defns[ 23]
#define UTZ_XIAN                &zone_defns[ 23]
#define UTZ_ZHENGZHOU           &zone_defns[ 23]

#define NUM_ZONE_NAMES 109
#define MAX_ZONE_NAME_LEN 17

const unsigned char zone_names[1056];
#endif /* _ZONES_H */